# Generated by Django 4.0.1 on 2022-01-24 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, max_length=100, verbose_name='тип документа')),
                ('object_name', models.TextField(blank=True, verbose_name='наименование ЮЛ, ИП, объекта')),
                ('exp_basis', models.TextField(blank=True, verbose_name='основание экспертизы')),
                ('exp_subject', models.TextField(blank=True, verbose_name='предмет экспертизы')),
                ('exp_result', models.TextField(blank=True, verbose_name='результат экспертизы')),
                ('executor_name', models.CharField(max_length=100, verbose_name='ФИО исполнителя')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='ФИО получателя')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='обновлено')),
            ],
        ),
    ]
