# Generated by Django 4.0.1 on 2022-01-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertises',
            name='creator',
            field=models.CharField(default=1, max_length=100, verbose_name='создатель экспертизы'),
            preserve_default=False,
        ),
    ]
