# Generated by Django 4.0.1 on 2022-01-25 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_alter_expertises_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertises',
            name='updated',
        ),
        migrations.AlterField(
            model_name='expertises',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='создано'),
        ),
    ]
