# Generated by Django 4.0.1 on 2022-01-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_remove_expertises_updated_alter_expertises_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertises',
            name='media',
            field=models.FileField(blank=True, upload_to='exps/%Y/%m/', verbose_name='прикрепленный файл'),
        ),
    ]
